---
- hosts: testserver
  remote_user: root
  tasks:
  - name: Web Server Installation
    apt: 
      name: nginx 
      state: latest
  - name: Modifying Nginx Conf File
    template:
      src: /etc/ansible/playbooks/infra/roles/nginx/template/nginx.j2
      dest: /etc/nginx/nginx.conf
    notify:
    - restart nginx
  - name: Ensure Webserver is running and boot enabled
    service: 
      name: nginx 
      state: started
      enabled: yes
  ...