---
- hosts: everest-app

  remote_user: ubuntu
  sudo: yes

  tasks:
  - name: Update The Repositories
    apt: update_cache=yes

  - name: Install Pre-requisites
    apt: name={{item}} state=present
    with_items:
    - git
    - python-pip
    - python-dev
    - build-essential

  - name: Changing opt Directory Ownership
    file:
      path: /opt
      state: directory
      owner: ubuntu
      sudo: yes

  - name: Creating Code Directory
    file:
      path: /opt/everest/sw
      state: directory
      mode: 0755
      sudo: yes

  - name: Creating Log Directory
    file:
      path: /opt/everest/var/log
      state: directory
      mode: 0755
      sudo: yes

  - name: Cloning The Code From Git Repo
    git: 
      repo: git@github.com:CredR/Everest-platform.git
      dest: /opt/everest/sw
      accept_hostkey: yes
      sudo: yes

  - name: Installing PIP requirements
    pip:
      requirements: /opt/everest/sw/Everest-platform/requirements.txt

  - name: Running the pyhton script
    script: /opt/everest/sw/Everest-platform/manage.py runserver 0.0.0.0:8001
...

