---
- hosts: everest-app

  remote_user: root

  tasks:
  - name: Update The Repositories
    apt: update_cache=yes

  - name: Install Pre-requisites
    apt: name={{item}} state=present
    with_items:
    - git
    - idle-python3.4
    - python-pip
    - python-dev
    - build-essential

  - name: Using Pyhton3.4 as Default
    shell: echo "alias python=python3" >> .bashrc

  - name: Changing opt Directory Ownership
    file:
      path: /opt
      state: directory
      owner: ubuntu
      group: ubuntu
      recurse: yes

  - name: Creating Code Directory
    file:
      path: /opt/everest/sw
      state: directory
      mode: 0755
      owner: ubuntu
      group: ubuntu

  - name: Creating Log Directory
    file:
      path: /opt/everest/var/log
      state: directory
      mode: 0755
      owner: ubuntu
      group: ubuntu

  - name: Cloning The Code From Git Repo
    git: 
      repo: ssh://git@github.com:CredR/Everest-platform.git 
      accept_hostkey: yes
      key_file: /root/.ssh/id_rsa.pub
      dest: /opt/everest/sw 
      force: yes

  - name: Installing PIP requirements
    pip:
      requirements: /opt/everest/sw/Everest-platform/requirements.txt

  - name: Running the pyhton script
    script: /opt/everest/sw/Everest-platform/manage.py runserver 0.0.0.0:8001
...
